### ISSUE TITLE
Syntax error 

### ISSUE THREAD

**Issue by miteshpant** [Vulnogram/Vulnogram#16]
XXXXXXXX:~/Vulnogram-0.0.6$ **node scripts/useradd.js tester tester@example.com Tester** sirt@example.com 1
/home/a10/Vulnogram-0.0.6/scripts/useradd.js:48
let newUser = new User({
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
_______________________________

:~/Vulnogram-0.0.6$ **make min**
node scripts/standalone.js
undefined:925
var unique = [...new Set(docs.map(item => item[column]).reduce((a, b) => a.concat(b), []))];
              ^^^

SyntaxError: Unexpected token ...
    at Function (native)
    at wrap (/home/a10/Vulnogram-0.0.6/node_modules/pug-runtime/wrap.js:6:10)
    at Object.exports.compile (/home/a10/Vulnogram-0.0.6/node_modules/pug/lib/index.js:262:7)
    at handleTemplateCache (/home/a10/Vulnogram-0.0.6/node_modules/pug/lib/index.js:215:25)
    at Object.exports.compileFile (/home/a10/Vulnogram-0.0.6/node_modules/pug/lib/index.js:356:10)
    at Object.<anonymous> (/home/a10/Vulnogram-0.0.6/scripts/standalone.js:10:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
Makefile:11: recipe for target 'standalone/index.html' failed
make: *** [standalone/index.html] Error 1

**Comment by chandanbn** [comment]
What version of nodejs are you running?
Looks like those messages could be from an old version of nodejs.

**Comment by miteshpant** [comment]
Thanks updating the version solved the issue
